stages:
  - build
  - deploy

build_box:
  stage: build
  image: ubuntu:latest
  before_script:
    - add-apt-repository --yes --update ppa:ansible/ansible
    - apt install -y ansible
    - wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt update && apt install -y vagrant virtualbox
  script:
    - vagrant up --privoder virtualbox 

deploy_vm:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y virtualbox vagrant sshpass # Установка sshpass
  script:
    - vagrant ssh ansible -c "echo 'Hello from web server' > /tmp/hello.txt"
    - vagrant ssh jenkins -c "sudo apt-get update"
    - vagrant ssh ansible -c "cat /tmp/hello.txt"
  dependencies:
    - build_box
  when: manual
  environment:
    name: production
  variables:
    VAGRANT_DEFAULT_PROVIDER: virtualbox

cache:
  paths:
    - .vagrant/
