vagrant_box: ubuntu/trusty64
vagrant_box_version: "20191107.0.0"
vagrant_ip: 192.168.56.
vagrant_hostname: vagrant
vagrant_memory: 4096
vagrant_directory: /vagrant
vagrant_cpu: 2
vagrant_box_check_update: false
vagrant_domain_name: sample.com
